(defun sayid-query-form-at-point ()
  (interactive)
  (let ((x (read (nrepl-dict-get (nrepl-send-sync-request (list
                                                             "op" "sayid-query-form-at-point"
                                                             "file" (buffer-file-name)
                                                             "line" (line-number-at-pos)))
                                   "value")))
          (orig-buf (current-buffer)))
      (pop-to-buffer "*sayid*")
      (erase-buffer)
      (insert x)
      (recenter -1)
      (ansi-color-apply-on-region (point-min) (point-max))
      (print orig-buf)
      (pop-to-buffer orig-buf)))
