(ns com.billpiel.sayid.expected-output1
  (:require [midje.sweet :refer :all]))

(def expected1
  "long values display nicely"
  ["\n " [:red] "v " [:bg-black :red] "com.billpiel.sayid.test.ns1/func-identity  "
   [:white] ":11" [nil] "\n " [:red] "| " [:red] "{" [:bold-off] "" [:yellow] ":a"
   [:bold-off] " " [:cyan] "1" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :b"
   [:bold-off] " " [:cyan] "2" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :c"
   [:bold-off] " " [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] " " [:cyan] "2"
   [:bold-off] " " [:cyan] "3" [:bold-off] " " [:cyan] "4" [:bold-off] " " [:cyan] "5" [:bold-off] " "
   [:cyan] "6" [:bold-off] " " [:cyan] "7" [:bold-off] "" [:red] "]" [:bold-off] ","
   [nil] "\n " [:red] "| " [:yellow] " :d" [:bold-off] " " [:red] "[" [:bold-off] ""
   [:cyan] "1" [:bold-off] " " [:cyan] "2" [:bold-off] " " [:cyan] "3" [:bold-off] " "
   [:cyan] "4" [:bold-off] " " [:cyan] "5" [:bold-off] " " [:cyan] "6" [:bold-off] " "
   [:cyan] "7" [:bold-off] "" [:red] "]" [:bold-off] "," [nil] "\n " [:red] "| "
   [:yellow] " :e" [:bold-off] " " [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] " "
   [:cyan] "2" [:bold-off] " " [:cyan] "3" [:bold-off] " " [:cyan] "4" [:bold-off] " "
   [:cyan] "5" [:bold-off] " " [:cyan] "6" [:bold-off] " " [:cyan] "7" [:bold-off] ""
   [:red] "]" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :f" [:bold-off] " "
   [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] " " [:cyan] "2" [:bold-off] " "
   [:cyan] "3" [:bold-off] " " [:cyan] "4" [:bold-off] " " [:cyan] "5" [:bold-off] " "
   [:cyan] "6" [:bold-off] " " [:cyan] "7" [:bold-off] "" [:red] "]" [:bold-off] ""
   [:red] "}" [:bold-off] "" [nil] "\n " [:red] "| " [:yellow] ":hello" [:bold-off] ""
   [nil] "\n " [:red] "| " [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 2" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 3"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 4" [:bold-off] "" [nil] "\n " [:red] "| "
   [:cyan] " 5" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 6" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 7" [:bold-off] "" [nil] "\n " [:red] "| "
   [:cyan] " 8" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 9" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 0" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 1"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 2" [:bold-off] "" [nil] "\n "
   [:red] "| " [:cyan] " 3" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 4"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 5" [:bold-off] "" [nil] "\n "
   [:red] "| " [:cyan] " 6" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 7" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 8" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 9"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 0" [:bold-off] "" [nil] "\n " [:red] "| "
   [:cyan] " 1" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 2" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 3" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 4"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 5" [:bold-off] "" [nil] "\n "
   [:red] "| " [:cyan] " 6" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 7" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 8" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 9"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 0" [:bold-off] "" [nil] "\n " [:red] "| "
   [:cyan] " 1" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 2" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 3" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 4"
   [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 5" [:bold-off] "" [nil] "\n " [:red] "| "
   [:cyan] " 6" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 7" [:bold-off] "" [nil] "\n "
   [:red] "| " [:cyan] " 8" [:bold-off] "" [nil] "\n " [:red] "| " [:cyan] " 9" [:bold-off] ""
   [nil] "\n " [:red] "| " [:cyan] " 0" [:bold-off] "" [:red] "]" [:bold-off] "" [nil] "\n "
   [:red] "| returned => \n " [:red] "| " [:red] "{" [:bold-off] "" [:yellow] ":a" [:bold-off] " "
   [:cyan] "1" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :b" [:bold-off] " "
   [:cyan] "2" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :c" [:bold-off] " "
   [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] " " [:cyan] "2" [:bold-off] " "
   [:cyan] "3" [:bold-off] " " [:cyan] "4" [:bold-off] " " [:cyan] "5" [:bold-off] " " [:cyan] "6"
   [:bold-off] " " [:cyan] "7" [:bold-off] "" [:red] "]" [:bold-off] "," [nil] "\n "
   [:red] "| " [:yellow] " :d" [:bold-off] " " [:red] "[" [:bold-off] "" [:cyan] "1"
   [:bold-off] " " [:cyan] "2" [:bold-off] " " [:cyan] "3" [:bold-off] " " [:cyan] "4"
   [:bold-off] " " [:cyan] "5" [:bold-off] " " [:cyan] "6" [:bold-off] " " [:cyan] "7" [:bold-off] ""
   [:red] "]" [:bold-off] "," [nil] "\n " [:red] "| " [:yellow] " :e" [:bold-off] " "
   [:red] "[" [:bold-off] "" [:cyan] "1" [:bold-off] " " [:cyan] "2" [:bold-off] " " [:cyan] "3"
   [:bold-off] " " [:cyan] "4" [:bold-off] " " [:cyan] "5" [:bold-off] " " [:cyan] "6"
   [:bold-off] " " [:cyan] "7" [:bold-off] "" [:red] "]" [:bold-off] "," [nil] "\n "
   [:red] "| " [:yellow] " :f" [:bold-off] " " [:red] "[" [:bold-off] "" [:cyan] "1"
   [:bold-off] " " [:cyan] "2" [:bold-off] " " [:cyan] "3" [:bold-off] " " [:cyan] "4"
   [:bold-off] " " [:cyan] "5" [:bold-off] " " [:cyan] "6" [:bold-off] " " [:cyan] "7"
   [:bold-off] "" [:red] "]" [:bold-off] "" [:red] "}" [:bold-off] "" [nil] "\n\n "
   [:red] "^ " [nil] "\n\n  " [nil] "\n"])
